import type { NextPage } from "next";
import Head from "next/head";
import {
  Box,
  Grid,
  Container,
  Flex,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuDivider,
} from "@chakra-ui/react";

import { IoPersonOutline } from "react-icons/io5";

import { authenticate, unauthenticate, currentUser } from "@onflow/fcl";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [user, setUser] = useState({ addr: null });

  useEffect(() => {
    currentUser().subscribe((currentUser) => {
      console.log(setUser);
      setUser(currentUser);
    });
  }, []);

  console.log(user);
  return (
    <>
      <Head>
        <title>MyNFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box borderBottom="1px" borderColor="gray.900">
        <Grid
          templateColumns="repeat(2, auto)"
          gap={6}
          paddingInline={10}
          paddingBlock={3}
          alignItems="center"
        >
          <Box>My NFT</Box>
          <Flex justifyContent="flex-end">
            {!user.addr && (
              <Button onClick={() => authenticate()} size="sm" variant="solid">
                Log In
              </Button>
            )}

            {user.addr && (
              <Menu>
                <MenuButton as={Button} icon={<IoPersonOutline />}></MenuButton>
                <MenuList>
                  <MenuItem>{user.addr}</MenuItem>
                  <MenuDivider />
                  <MenuItem onClick={() => unauthenticate()}>Sign out</MenuItem>
                </MenuList>
              </Menu>
            )}
          </Flex>
        </Grid>
      </Box>

      <Container maxW="container.xl">
        <Grid templateColumns="repeat(2, 1fr)" gap={6}>
          <Box>Hello World!</Box>
        </Grid>
      </Container>
    </>
  );
};

export default Home;
