import type { NextPage } from "next";
import Head from "next/head";
import { Box, Grid, Container } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl">
        <Grid templateColumns="repeat(2, 1fr)" gap={6}>
          <Box>Hello World!</Box>
        </Grid>
      </Container>
    </>
  );
};

export default Home;
